### ISSUE TITLE
Chrome: Third-party cookie will be blocked. Learn more in the Issues tab.

### ISSUE THREAD

**Issue by abuwho** [yandex/metrica-tag#14]
Hello. 

On my website, I am facing this issue. It seems Chrome is not allowing Yandex's 3rd party cookies and will not allow them in the future. 

```
Reading cookie in cross-site context will be blocked in future Chrome versions
Cookies with the SameSite=None; Secure and not Partitioned attributes that operate in cross-site contexts are third-party cookies. In future Chrome versions, reading third-party cookies will be blocked. This behavior protects user data from cross-site tracking.
Please refer to the article linked to learn more about preparing your site to avoid potential breakage.
13 cookies
10 requests
```

What is the ideal way around this? Is it going to be solved if we use `Partitioned` attribute to the cookies? (i.e. CHIPS)

**Comment by sabio-yateam** [comment]
It's not related to `Yandex's 3rd party cookies`, but rather to all 3rd parties. Moreover it's not an issue - the message just informs about the way Google is going to treat 3rd party cookies in the nearest future.

Since the cookies set by metrica-tag are 1st party and do not affect your page functionality, there is no need to do anything.

BTW, the message informs of the server-set Yandex cookies, which are not controlled under this repo. Thus you won't be able to add any atrtibutes to them.
